apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: "POST"

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: host.docker.internal:5432
    database: educational_platform_dev
    user: eduplatform
    secureJsonData:
      password: eduplatform2024
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1400
      timescaledb: false
    editable: true

  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis://host.docker.internal:6379
    jsonData:
      acl: false
      poolSize: 5
      timeout: 10
      pingInterval: 0
      pipelineWindow: 0
    editable: true